### ISSUE TITLE
Update library to support mysqlclient>=1.4.0

### ISSUE THREAD

**Issue by arikfr** [memsql/memsql-python#18]
In version 1.4.0 of `mysqlclient` they moved the `_mysql` module into the `MySQLdb` package (PyMySQL/mysqlclient-python#293).

Will you be interested in accepting a pull request that adds support for this version of `mysqlclient`? It can be done in a backward compatible way:

```python
try:
    import _mysql
except ImportError:
    from MySQLdb import _mysql
```

**Comment by arikfr** [comment]
It looks like it will require an update in `memsql.common.conversions` as well, as the current code assumes converters are arrays.

**Comment by carlsverre** [comment]
Sorry for the huge delay on this - please check it out and let me know if you run into any issues.
