### ISSUE TITLE
MySQLdb._exceptions.OperationalError: (2012, 'Error in server handshake')

### ISSUE THREAD

**Issue by ngarg-panw** [memsql/memsql-python#22]
In my Python script, I am constantly getting 
`  File "/Users/user/PycharmProjects/memsqlKafka/startup_try.py", line 17, in main
    conn = database.connect(host=HOST, port=PORT, database=DATABASE, user=USER, password=PASSWORD)
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 19, in connect
    return Connection(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 62, in __init__
    self.reconnect()
  File "/usr/local/lib/python3.8/site-packages/memsql/common/database.py", line 93, in reconnect
    conn = _mysql.connect(**self._db_args)
MySQLdb._exceptions.OperationalError: (2012, 'Error in server handshake')`

Its a simple file with only the connection string:
`
from memsql.common import database

def main():

  HOST = '127.0.0.1'
  PORT = 3306
  USER = 'root'
  PASSWORD = 'password'
  DATABASE = 'test_db'

  conn = database.connect(host=HOST, port=PORT, database=DATABASE, user=USER, password=PASSWORD)`

I am using memsql 3.1.0 and MySqlClient 2.1.0

I am able to connect to my database using the same details via tableplus

**Comment by carlsverre** [comment]
Hi @ngarg-panw, based on the error I would guess that this issue is SSL related. Can you confirm that there is a SingleStore instance running at root:password@127.0.0.1? Can you also verify that you can connect to the SingleStore instance using the regular mysql cli? If you need a mysql cli I suggest using mariadb-client.

Also, are you running anything inside Docker or is everything running directly on the host?

**Comment by ngarg-panw** [comment]
Singlestore instance is running inside docker and I am using memsql-cluster-in-a-box.

I did try from the local and getting the same error:
`mysql --host=127.0.0.1 --user=root --password=pass@22 app
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 2012 (HY000): Error in server handshake`

You might be right about ssl. Thanks for the pointer. Will debug from here.

**Comment by carlsverre** [comment]
Sounds good, make sure you are using the latest singlestore cluster in a box image. Docs here: https://github.com/memsql/deployment-docker#running-the-cluster-in-a-box-image

I'll close this for now, feel free to reopen if you can't resolve the issue.
