### ISSUE TITLE
Extending character set to utf8mb4

### ISSUE THREAD

**Issue by Nikita-Yasenkov** [memsql/memsql-python#28]
I was updating my python to 3.9 for my personal project and was having the following error:

**_(1115, "Unknown character set: 'utf8mb3'")_**

So I modified "memsql/common/database.py" line: 72 and extended the character set to "utf8mb4" 

Now I suggest this change to the repo in order to reuse the library. Since I modified the library locally, I would have to modify it each time when I deploy my project on the server or another machine. Please consider this edit. Thanks!

**Comment by carlsverre** [comment]
This repo is being deprecated in deference to our new driver: https://github.com/singlestore-labs/singlestore-python

The new driver is in beta but will be production ready very soon. In the meantime please use the mysqlclient or PyMySQL drivers instead of this one.

Thanks
