### ISSUE TITLE
Feature: Jupysql integration

### ISSUE THREAD

**Issue by idomic** [memsql/memsql-python#29]
## Description
It'd be great to see a tutorial or documentation of the 2 frameworks.
Probably a user working locally via a jupyter notebook and [jupysql](https://github.com/ploomber/jupysql) to query and perform EDA/modeling work.

## Motivation
Please provide the following for the desired feature or change:

A detailed explanation on querying via SQL.
Plotting via sql.
Using Jupyter notebooks to query.

Happy to work on the PR!

**Comment by kesmit13** [comment]
Development on a Python client for SingleStoreDB has moved to https://github.com/singlestore-labs/singlestoredb-python. There is also a SQLAlchemy dialect which uses that client at https://github.com/singlestore-labs/sqlalchemy-singlestoredb. Using that dialect, I think you should be able to use jupysql by following these instructions: https://jupysql.readthedocs.io/en/latest/connecting.html#using-an-existing-sqlalchemy-engine-engine.

**Comment by idomic** [comment]
Should I move the issue to the new repo?

I was looking to contribute an Docs example/blog post to SingleStoreDB.
The main advantage IMO is better capabilities over sqlalchemy, such as direct plotting, complex queries and multiple connections.

**Comment by kesmit13** [comment]
Yeah, if you could move it to the other project, we can look into it. Thanks.

**Comment by idomic** [comment]
Moved
