### ISSUE TITLE
Any driver of memsql for Golang?

### ISSUE THREAD

**Issue by ghost** [memsql/memsql-python#3]
Although you claimed that memsql is used just like mysql, I came across a problem:
`Mysql Error 1615: Prepared statement needs to be re-prepared`

It's tested with the most commonly used driver for mysql in Golang:
`https://github.com/go-sql-driver/mysql`

And my code is as follow:
![68665ef9-f591-4466-9697-efbb50660c13](https://f.cloud.github.com/assets/5228795/2490492/d03c15ee-b1ad-11e3-84fd-2914d64ee727.png)

It is simple as it looks and code is bug free I think.
So, would you mind providing a golang driver?

**Comment by elimisteve** [comment]
@ankrgyl Was this discussion moved to your support forums? I, too, would like a Go MemSQL driver

**Comment by carlsverre** [comment]
@elimisteve MemSQL works with github.com/go-sql-driver/mysql.  The only tweak you have to make is specifying `interpolateParams=true` in the connection string.  We use go-sql-driver/mysql internally and have found no issues.

**Comment by Hokutosei** [comment]
came across on this today,. any news about a go driver/dialect for memsql? it would be nice to have one... we use go primarily, and I am looking on different solutions for datastore..giving this a shot..

**Comment by choochootrain** [comment]
@Hokutosei see carl's comment above: `go-sql-driver/mysql` is the driver we use internally
