### ISSUE TITLE
Cannot install Memsql.common 

### ISSUE THREAD

**Issue by sajeetharan** [memsql/memsql-python#6]
When i run the application which uses this library, getting an error memsql.common not found and when i tried to install using a pip command, the following error occurs, what could be the reason?

root@digin-io-qa:/usr/local/DigInEngine#  pip install memsql.common.py
Collecting memsql.common.py
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/uti                                                                                        l/ssl_.py:318: SNIMissingWarning: An HTTPS request has been made, but the SNI (S                                                                                        ubject Name Indication) extension to TLS is not available on this platform. This                                                                                         may cause the server to present an incorrect TLS certificate, which can cause v                                                                                        alidation failures. You can upgrade to a newer version of Python to solve this.                                                                                         For more information, see https://urllib3.readthedocs.org/en/latest/security.htm                                                                                        l#snimissingwarning.
  SNIMissingWarning
/usr/local/lib/python2.7/dist-packages/pip/_vendor/requests/packages/urllib3/uti                                                                                        l/ssl_.py:122: InsecurePlatformWarning: A true SSLContext object is not availabl                                                                                        e. This prevents urllib3 from configuring SSL appropriately and may cause certai                                                                                        n SSL connections to fail. You can upgrade to a newer version of Python to solve                                                                                         this. For more information, see https://urllib3.readthedocs.org/en/latest/secur                                                                                        ity.html#insecureplatformwarning.
  InsecurePlatformWarning
  Could not find a version that satisfies the requirement memsql.common.py (from                                                                                         versions: )
No matching distribution found for memsql.common.py

**Comment by carlsverre** [comment]
The package on pypi is called "memsql" so you should say `pip install memsql`
